name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp bin/normelog dist/
          chmod +x dist/normelog

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/normelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
